In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X, y = np.array(iris.data), np.array(iris.target)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
y_train = keras.utils.to_categorical(y_train)
y_test = keras.utils.to_categorical(y_test)

In [4]:

net = tf.keras.models.Sequential([
    tf.keras.layers.Dense(3, input_dim=4, activation = 'relu'),] + 
    [ tf.keras.layers.Dense(3, activation = 'relu') for _ in range(8)] +
    [tf.keras.layers.Dense(3, activation='softmax'),])

In [5]:
net.compile(loss='categorical_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

In [6]:
net.fit(X_train, y_train, epochs=150, batch_size=24)

Epoch 1/150
5/5 [==============================] - 1s 6ms/step - loss: 1.0988 - accuracy: 0.3250
Epoch 2/150
5/5 [==============================] - 0s 5ms/step - loss: 1.0986 - accuracy: 0.3500
Epoch 3/150
5/5 [==============================] - 0s 4ms/step - loss: 1.0986 - accuracy: 0.3500
Epoch 4/150
5/5 [==============================] - 0s 4ms/step - loss: 1.0985 - accuracy: 0.3500
Epoch 5/150
5/5 [==============================] - 0s 6ms/step - loss: 1.0985 - accuracy: 0.3500
Epoch 6/150
5/5 [==============================] - 0s 4ms/step - loss: 1.0985 - accuracy: 0.3500
Epoch 7/150
5/5 [==============================] - 0s 5ms/step - loss: 1.0984 - accuracy: 0.3500
Epoch 8/150
5/5 [==============================] - 0s 5ms/step - loss: 1.0984 - accuracy: 0.3500
Epoch 9/150
5/5 [==============================] - 0s 6ms/step - loss: 1.0984 - accuracy: 0.3500
Epoch 10/150
5/5 [==============================] - 0s 4ms/step - loss: 1.0983 - accuracy: 0.3500
Epoch 11/150
5/5 [===========

In [7]:
score = net.evaluate(X_test, y_test, verbose=0)
print("Test loss:", format(score[0],".4f"))
print("Test accuracy:", score[1])

Test loss: 1.1057
Test accuracy: 0.2666666805744171


In [8]:
y_softmax = net.predict(X_test)

y_pc = np.argmax(y_softmax, axis = -1)

y_pred = keras.utils.to_categorical(y_pc)

Cmat = tf.math.confusion_matrix(y_test.argmax(axis=-1),y_pred.argmax(axis=-1))
print(Cmat)

tf.Tensor(
[[ 0  0 12]
 [ 0  0 10]
 [ 0  0  8]], shape=(3, 3), dtype=int32)
