In [1]:
# Setup
import numpy as np

In [2]:
# Question 1 part (a)

# Column vector a
a = np.array([1, -2, 3, 2]).reshape((4, 1))

# Column vector b
b = np.array([1, -2, 3, 2]).reshape((4, 1))

# Computing c = a @ b.T
c = a @ b.T
print(f'Dimensions of c = {c.shape}')
print(f'c =\n{c}')

# Computing d = a.T @ b
d = a.T @ b
print(f'Dimensions of d = {d.shape}')
print(f'd = {d}')

Dimensions of c = (4, 4)
c =
[[ 1 -2  3  2]
 [-2  4 -6 -4]
 [ 3 -6  9  6]
 [ 2 -4  6  4]]
Dimensions of d = (1, 1)
d = [[18]]


In [3]:
# Question 1 part (b)

# If the equation E = ADB = sum(d[i, i] * (a[i] @ b[i].T)) is true,
# it should be true for any random value in the matrices.
# This is obviously not a proof, we could just get lucky,
# the proof is given after this verification script on random numbers

# Matrix A, a (3, 2) matrix
A = np.random.random((3, 2))
print(f'A =\n{A}', end='\n\n')

# Matrix D, a (2, 2) diagonal matrix
D = np.diag(np.random.random((2, )))
print(f'D =\n{D}', end='\n\n')

# Matrix B, a (2, 4) matrix
B = np.random.random((2, 4))
print(f'B =\n{B}', end='\n\n')

# E is a list of two matrices
# E[0] is the matrix computed using E = A @ D @ B
# E[1] is the matrix computed using E = sum(d[i, i] * (a[i] @ b[i].T))
E = [None] * 2

E[0] = A @ D @ B
print(f'E[0] = \n{E[0]}', end='\n\n')

# To compute E, well add elements according to the formula,
# starting from a Null matrix of dimensions (3, 4)
# A @ D @ B => [(3, 2) @ (2, 2)] @ (2, 4) => (3, 2) @ (2, 4)
# A @ D @ B => (3, 4)
E[1] = np.zeros((3, 4))

# Performing the summation
for i in range(2): # indexes start from 0 instead of 1
    # D[i, i] selects the diagonal elements
    D_i = D[i, i]
    
    # A[:, i] selects the ith columns from A 
    # reshaping to make it compatible with mat_mul
    A_i = (_ := A[:, i]).reshape((_.shape[0], 1))
    
    # B[i] selects the ith row from B
    # reshaping to make it compatible with mat_mul
    B_i = (_ := B[i]).reshape((1, _.shape[0], ))
    
    # Summing after the operations
    E[1] += D_i * (A_i @ B_i)

print(f'E[1] = \n{E[1]}', end='\n\n')

# We can check if the matrices E[0] and E[1] are equal
# To avoid errors arising from floating point numbers,
# we will use the numpy.isclose() method
equal_Es = np.isclose(*E)

print(f'E[0] == E[1] =\n{equal_Es}', end='\n\n')

if equal_Es.all():
    print('Numerically, this is accurate for randomly generated number')
else:
    print(
        'Numerically, this did not work for',
        f'A =\n{A}',
        f'D =\n{D}',
        f'B =\n{B}',
        sep='\n'
    )

A =
[[0.17751033 0.9574315 ]
 [0.8663529  0.51359192]
 [0.03996149 0.25309533]]

D =
[[0.62280832 0.        ]
 [0.         0.89419172]]

B =
[[0.01979454 0.14445648 0.04444382 0.09481595]
 [0.30673953 0.69147589 0.37542403 0.35451482]]

E[0] = 
[[0.26479647 0.60796177 0.32632425 0.31399219]
 [0.15155059 0.3955047  0.19639398 0.21397082]
 [0.06991264 0.16008716 0.0860705  0.0825921 ]]

E[1] = 
[[0.26479647 0.60796177 0.32632425 0.31399219]
 [0.15155059 0.3955047  0.19639398 0.21397082]
 [0.06991264 0.16008716 0.0860705  0.0825921 ]]

E[0] == E[1] =
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

Numerically, this is accurate for randomly generated number


### Question 1 part (b) Mathematical solution

<div style="font-size:15px;">
Let
$A_{3 \times 2} = \begin{bmatrix}a_{11} & a_{12} \\ a_{21} & a_{22} \\ a_{31} & a_{32} \end{bmatrix}$, 
$D_{2 \times 2} = \begin{bmatrix}d_{11} & 0 \\ 0 & d_{22} \end{bmatrix}$ and 
$B_{2 \times 4} = \begin{bmatrix}b_{11} & b_{12} & b_{13} & b_{14} \\ b_{21} & b_{22} & b_{23} & b_{24} \end{bmatrix}$<br>
<br>
To show, $E = ADB = \displaystyle \sum_{i=1}^{2}d_{ii}a_{i}b_{i}^{T}$<br><br>
So, first let's compute $AD$,<br>
$AD = \begin{bmatrix}a_{11} & a_{12} \\ a_{21} & a_{22} \\ a_{31} & a_{32} \end{bmatrix}
\times
\begin{bmatrix}d_{11} & 0 \\ 0 & d_{22} \end{bmatrix}
$<br>
$AD = \begin{bmatrix} 
a_{11} \cdot d_{11} & a_{12} \cdot d_{12} \\
a_{21} \cdot d_{11} & a_{22} \cdot d_{12} \\
a_{31} \cdot d_{11} & a_{32} \cdot d_{12} 
\end{bmatrix}$<br><br>
Now that we know AD, let's compute $ABD$<br>
$ABD = AD \cdot B = \begin{bmatrix} 
a_{11} \cdot d_{11} & a_{12} \cdot d_{12} \\
a_{21} \cdot d_{11} & a_{22} \cdot d_{12} \\
a_{31} \cdot d_{11} & a_{32} \cdot d_{12} 
\end{bmatrix} \times 
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14} \\
b_{21} & b_{22} & b_{23} & b_{24}
\end{bmatrix}$<br>
$ABD = \begin{bmatrix} 
a_{11}  d_{11}  b_{11} + a_{12}  d_{22}  b_{21} &
a_{11}  d_{11}  b_{12} + a_{12}  d_{22}  b_{22} &
a_{11}  d_{11}  b_{13} + a_{12}  d_{22}  b_{23} &
a_{11}  d_{11}  b_{14} + a_{12}  d_{22}  b_{24} \\
a_{21}  d_{11}  b_{11} + a_{22}  d_{22}  b_{21} &
a_{21}  d_{11}  b_{12} + a_{22}  d_{22}  b_{22} &
a_{21}  d_{11}  b_{13} + a_{22}  d_{22}  b_{23} &
a_{21}  d_{11}  b_{14} + a_{22}  d_{22}  b_{24} \\
a_{31}  d_{11}  b_{11} + a_{32}  d_{22}  b_{21} &
a_{31}  d_{11}  b_{12} + a_{32}  d_{22}  b_{22} &
a_{31}  d_{11}  b_{13} + a_{32}  d_{22}  b_{23} &
a_{31}  d_{11}  b_{14} + a_{32}  d_{22}  b_{24} \\
\end{bmatrix}
$&emsp;&emsp;...1<br><br>
Now, let's compute $E$ using $E = \displaystyle \sum_{i=1}^{2}d_{ii}a_{i}b_{i}^{T}$<br>
$E = d_{11}a_{1}b_{1}^{T} + d_{22}a_{2}b_{2}^{T}$<br>
<br>
Computing individual components of $E$,<br>
$d_{11}a_{1}b_{1}^{T} = d_{11} \cdot 
\begin{bmatrix} a_{11} \\ a_{21} \\ a_{31} \end{bmatrix} \times
\begin{bmatrix} b_{11} & b_{12} & b_{13} & b_{14} \end{bmatrix}
$<br>
$d_{11}a_{1}b_{1}^{T} = d_{11} \cdot
\begin{bmatrix}
a_{11}b_{11} & a_{11}b_{12} & a_{11}b_{13} & a_{11}b_{14} \\
a_{21}b_{11} & a_{21}b_{12} & a_{21}b_{13} & a_{21}b_{14} \\
a_{31}b_{11} & a_{31}b_{12} & a_{31}b_{13} & a_{31}b_{14} \\
\end{bmatrix}
$<br>
$d_{11}a_{1}b_{1}^{T} =
\begin{bmatrix}
d_{11}a_{11}b_{11} & d_{11}a_{11}b_{12} & d_{11}a_{11}b_{13} & d_{11}a_{11}b_{14} \\
d_{11}a_{21}b_{11} & d_{11}a_{21}b_{12} & d_{11}a_{21}b_{13} & d_{11}a_{21}b_{14} \\
d_{11}a_{31}b_{11} & d_{11}a_{31}b_{12} & d_{11}a_{31}b_{13} & d_{11}a_{31}b_{14} \\
\end{bmatrix}
$&emsp;&emsp;&emsp;...2<br>
<br>
$d_{22}a_{2}b_{2}^{T} = d_{22} \cdot 
\begin{bmatrix} a_{12} \\ a_{22} \\ a_{32} \end{bmatrix} \times
\begin{bmatrix} b_{21} & b_{22} & b_{23} & b_{24} \end{bmatrix}
$<br>
$d_{22}a_{2}b_{2}^{T} = d_{22} \cdot
\begin{bmatrix}
a_{12}b_{21} & a_{12}b_{22} & a_{12}b_{23} & a_{12}b_{24} \\
a_{22}b_{21} & a_{22}b_{22} & a_{22}b_{23} & a_{22}b_{24} \\
a_{32}b_{21} & a_{32}b_{22} & a_{32}b_{23} & a_{32}b_{24} \\
\end{bmatrix}
$<br>
$d_{22}a_{2}b_{2}^{T} =
\begin{bmatrix}
d_{22}a_{12}b_{21} & d_{22}a_{12}b_{22} & d_{22}a_{12}b_{23} & d_{22}a_{12}b_{24} \\
d_{22}a_{22}b_{21} & d_{22}a_{22}b_{22} & d_{22}a_{22}b_{23} & d_{22}a_{22}b_{24} \\
d_{22}a_{32}b_{21} & d_{22}a_{32}b_{22} & d_{22}a_{32}b_{23} & d_{22}a_{32}b_{24} \\
\end{bmatrix}$&emsp;&emsp;&emsp;...3<br>
<br>
Using Equation 2 and 3,<br>
$E = d_{11}a_{1}b_{1}^{T} + d_{22}a_{2}b_{2}^{T}$<br><br>
$E = 
\begin{bmatrix}
d_{11}a_{11}b_{11} & d_{11}a_{11}b_{12} & d_{11}a_{11}b_{13} & d_{11}a_{11}b_{14} \\
d_{11}a_{21}b_{11} & d_{11}a_{21}b_{12} & d_{11}a_{21}b_{13} & d_{11}a_{21}b_{14} \\
d_{11}a_{31}b_{11} & d_{11}a_{31}b_{12} & d_{11}a_{31}b_{13} & d_{11}a_{31}b_{14} \\
\end{bmatrix}
+ 
\begin{bmatrix}
d_{22}a_{12}b_{21} & d_{22}a_{12}b_{22} & d_{22}a_{12}b_{23} & d_{22}a_{12}b_{24} \\
d_{22}a_{22}b_{21} & d_{22}a_{22}b_{22} & d_{22}a_{22}b_{23} & d_{22}a_{22}b_{24} \\
d_{22}a_{32}b_{21} & d_{22}a_{32}b_{22} & d_{22}a_{32}b_{23} & d_{22}a_{32}b_{24} \\
\end{bmatrix}
$<br><br>
$
E = \begin{bmatrix} 
d_{11}  a_{11}  b_{11} + d_{22}  a_{12}  b_{21} &
d_{11}  a_{11}  b_{12} + d_{22}  a_{12}  b_{22} &
d_{11}  a_{11}  b_{13} + d_{22}  a_{12}  b_{23} &
d_{11}  a_{11}  b_{14} + d_{22}  a_{12}  b_{24} \\
d_{11}  a_{21}  b_{11} + d_{22}  a_{22}  b_{21} &
d_{11}  a_{21}  b_{12} + d_{22}  a_{22}  b_{22} &
d_{11}  a_{21}  b_{13} + d_{22}  a_{22}  b_{23} &
d_{11}  a_{21}  b_{14} + d_{22}  a_{22}  b_{24} \\
d_{11}  a_{31}  b_{11} + d_{22}  a_{32}  b_{21} &
d_{11}  a_{31}  b_{12} + d_{22}  a_{32}  b_{22} &
d_{11}  a_{31}  b_{13} + d_{22}  a_{32}  b_{23} &
d_{11}  a_{31}  b_{14} + d_{22}  a_{32}  b_{24} \\
\end{bmatrix}
$&emsp;&emsp;...4<br>
<br>
Comparing elementwise, we can easily verify that $E$ obtained in <em>Equation $4$</em> is equivalent to the $E$ obtained in <em>Equation $1$</em><br>
Therefore, $E = ADB = \displaystyle \sum_{i=1}^{2}d_{ii}a_{i}b_{i}^{T}$ is $\text{True}$
</div>

In [4]:
# Question 1 part (c)

a = np.arange(20)
A = a.reshape((5, 4))
print(f'A =\n{A}')

A =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [5]:
# Question 1 part (d)

hadamard_product = A * A
print(f'Hadamard Product =\n{hadamard_product}')

Hadamard Product =
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


In [6]:
# Question 2 part (a)

b = np.arange(24)
B = b.reshape((2, 3, 4))

print(f'B = \n{B}')

B = 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
# Question 2 part (b)

B_sum = np.sum(B)

print(f'Sum of elements in B = {B_sum}')

Sum of elements in B = 276


In [8]:
# Question 2 part (c)

C, D = B # obtaining C and D via tuple unpacking

print(f'C =\n{C}')
print(f'D =\n{D}')

C =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
D =
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Question 3

<table style="text-align:center;font-size:16px;">
  <tr>
    <th>Outlook</th>
    <th>Temperature</th>
    <th>Humidity</th>
    <th>Wind</th>
    <th>Played Football (yes/no)</th>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Hot</td>
    <td>High</td>
    <td>Weak</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Hot</td>
    <td>High</td>
    <td>Strong</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Hot</td>
    <td>High</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Mild</td>
    <td>High</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Strong</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Strong</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Mild</td>
    <td>High</td>
    <td>Weak</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Mild</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Mild</td>
    <td>Normal</td>
    <td>Strong</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Mild</td>
    <td>High</td>
    <td>Strong</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Hot</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Mild</td>
    <td>High</td>
    <td>Strong</td>
    <td>No</td>
  </tr>
</table>

In [9]:
# Setup
import math

table = {
    "Outlook": [
        'Sunny', 'Sunny', 'Overcast',
        'Rain', 'Rain', 'Rain', 'Overcast',
        'Sunny', 'Sunny', 'Rain', 'Sunny',
        'Overcast', 'Overcast', 'Rain',
    ],

    "Temperature": [
        "Hot", "Hot", "Hot", "Mild", "Cool",
        "Cool", "Cool", "Mild", "Cool", "Mild",
        "Mild", "Mild", "Hot", "Mild",
    ],

    "Humidity": [
        "High", "High", "High", "High", "Normal",
        "Normal", "Normal", "High", "Normal",
        "Normal", "Normal", "High", "Normal", "High",
    ],

    "Wind": [
        "Weak", "Strong", "Weak", "Weak", "Weak",
        "Strong", "Strong", "Weak", "Weak", "Weak",
        "Strong", "Strong", "Weak", "Strong",
    ],

    "Played": [
        "No", "No", "Yes", "Yes", "Yes", "No", "Yes",
        "No", "Yes", "Yes", "Yes", "Yes", "Yes", "No",
    ],
}

# Function that takes in iterables and predicates (conditions) to
# filter values by the predicate and return the required probability
def pr(iterable: 'Iterable[str]', predicate: callable) -> float:
    return sum((1 for i in iterable if predicate(i))) / len(iterable)

In [10]:
# Question 3 part (a)

# Finding probabilty of High Humidity
p_high = pr(table["Humidity"], lambda x: x == "High")
print("Pr. {Humidity = High} = ", p_high)

Pr. {Humidity = High} =  0.5


In [11]:
# Question 3 part (b)

# Finding probabilty of a Sunny Outlook and Normal Humidity
p_sunny_normal = pr(
    list(zip(table["Outlook"], table["Humidity"])),
    lambda x: x[0] == "Sunny" and x[1] == "Normal"
)
# Rounded to 6 decimal places
print("Pr. {Outlook = Sunny AND Humidity = Normal} = ", f'{p_sunny_normal:.6}')

Pr. {Outlook = Sunny AND Humidity = Normal} =  0.142857


In [12]:
# Question 3 part (c)

# Finding probabilty of Cold Temperatures or Weak Winds
p_cold_weak = pr(
    list(zip(table["Temperature"], table["Wind"])),
    lambda x: x[0] == "Cold" or x[1] == "Weak"
)
# Rounded to 6 decimal places
print("Pr. {Temperature = Cold OR Wind = Weak} = ", f'{p_cold_weak:.6}')

Pr. {Temperature = Cold OR Wind = Weak} =  0.571429


In [13]:
# Question 3 part (d)

# Finding probabilty of playing football given Humidity is high
# We can find this using the formula,
# P(A|B) = P(A and B) / P(B)

p_played_high = pr(
    list(zip(table["Played"], table["Humidity"])),
    lambda x: x[0] == "Yes" and x[1] == "High" # P(A and B)
) / pr(table["Humidity"], lambda x: x == "High") # P(B)

# Rounded to 6 decimal places
print("Pr. {Play = Yes | Humidity = High} = ", f'{p_played_high:.6}')

Pr. {Play = Yes | Humidity = High} =  0.428571


In [14]:
# Question 3 part (e)

# Finding probabilty of high Humidity, given football was played
# We can find this using the formula,
# P(A|B) = P(A and B) / P(B)

p_high_played = pr(
    list(zip(table["Humidity"], table["Played"])),
    lambda x: x[0] == "High" and x[1] == "Yes" # P(A and B)
) / pr(table["Played"], lambda x: x == "Yes") # P(B)

# Rounded to 6 decimal places
print("Pr. {Play = Yes | Humidity = High} = ", f'{p_high_played:.6}')

Pr. {Play = Yes | Humidity = High} =  0.333333


In [15]:
# Question 3 part (f)

# Finding the entropy of the outcome of play

def information(x: float) -> float:
    return -math.log(x)

def entropy(pdf: callable, outcomes: set[str]) -> float:
    return sum(((p := pdf(x)) * information(p) for x in outcomes))

entropy_play = entropy(
    lambda x: pr(table["Played"], lambda y: x == y),
    set(table["Played"])
)

# Rounded to 7 decimal places
print("Entropy of the outcome of play = ", f'{entropy_play:.7}')

Entropy of the outcome of play =  0.6517566


In [16]:
# Question 4 

# Setup
filename = 'iris.csv'
iris = np.genfromtxt(filename, delimiter=",")

In [17]:
# Question 4 part(a)
# Calcuating the mean matrix

# Mean vector for each label
for x, y in enumerate(range(3), 1):
    mean = np.mean(iris[y*50:(y+1)*50, :-1], axis=0)
    print(
        *(f'Mean for Label {x}\'s Feature {i}: {m:.7}'
          for i, m in enumerate(mean, 1))
        , sep='\n', end='\n\n'
    )

Mean for Label 1's Feature 1: 5.006
Mean for Label 1's Feature 2: 3.418
Mean for Label 1's Feature 3: 1.464
Mean for Label 1's Feature 4: 0.244

Mean for Label 2's Feature 1: 5.936
Mean for Label 2's Feature 2: 2.77
Mean for Label 2's Feature 3: 4.26
Mean for Label 2's Feature 4: 1.326

Mean for Label 3's Feature 1: 6.588
Mean for Label 3's Feature 2: 2.974
Mean for Label 3's Feature 3: 5.552
Mean for Label 3's Feature 4: 2.026



In [31]:
# Question 4 part (a) continued
# Calculating the covariance matrix

def E(X: np.ndarray) -> float:
    '''
    Params:
        | X: np.ndarray | The vector to compute the expectation for
    Returns:
        float: expected value of X
    
    This function computes the expected value for
    the random variable X.
    Since X is a vector of discrete values,
    Expectation of X is equal to the mean of X
    '''
    return np.mean(X)

def covariance(A: np.ndarray, B: np.ndarray) -> float:
    '''
    Params:
        | A: np.ndarray | Vector of Random Variable A values
        | B: np.ndarray | Vector of Random Variable B values
    Returns:
        float: Covariance of A and B
    
    This function computes the covariance between A and B
    using the formula
    Cov(A,B) = E(AB) - E(A)E(B)
    Cov: Covariance
     E : Expectation
    '''
    return E(A*B) - E(A) * E(B)

def cov(X: np.ndarray) -> np.ndarray:
    '''
    Params:
        | X: np.ndarray | The 2D array to calculate covariance for
    Returns:
        np.ndarray: The covariance matrix
    
    Calculates the covariance matrix for the given matrix X
    '''
    # number of features, taken as the second dimension
    # f = len(axis=1) = X.shape[1]
    f = X.shape[1]
    m = np.zeros((f, f))
    for i in range(m.shape[0]):
        m[i, i] = covariance(X[:, i], X[:, i])
        for j in range(i):
            m[i,j] = covariance(X[:, i], X[:, j])
            m[j, i] = m[i, j]
    return m

for x, y in enumerate(range(3), 1):
    c = cov(iris[y * 50 : (y+1) * 50, :-1])
    print(f'Covariance Matrix for Label {x} =', c, sep='\n', end='\n\n')

Covariance Matrix for Label 1 =
[[0.121764 0.098292 0.015816 0.010336]
 [0.098292 0.142276 0.011448 0.011208]
 [0.015816 0.011448 0.029504 0.005584]
 [0.010336 0.011208 0.005584 0.011264]]

Covariance Matrix for Label 2 =
[[0.261104 0.08348  0.17924  0.054664]
 [0.08348  0.0965   0.081    0.04038 ]
 [0.17924  0.081    0.2164   0.07164 ]
 [0.054664 0.04038  0.07164  0.038324]]

Covariance Matrix for Label 3 =
[[0.396256 0.091888 0.297224 0.048112]
 [0.091888 0.101924 0.069952 0.046676]
 [0.297224 0.069952 0.298496 0.047848]
 [0.048112 0.046676 0.047848 0.073924]]

