In [1]:
# Setup
import numpy as np

In [2]:
# Question 1 part (a)

# Column vector a
a = np.array([1, -2, 3, 2]).reshape((4, 1))

# Column vector b
b = np.array([1, -2, 3, 2]).reshape((4, 1))

# Computing c = a @ b.T
c = a @ b.T
print(f'Dimensions of c = {c.shape}')
print(f'c =\n{c}')

# Computing d = a.T @ b
d = a.T @ b
print(f'Dimensions of d = {d.shape}')
print(f'd = {d}')

Dimensions of c = (4, 4)
c =
[[ 1 -2  3  2]
 [-2  4 -6 -4]
 [ 3 -6  9  6]
 [ 2 -4  6  4]]
Dimensions of d = (1, 1)
d = [[18]]


In [3]:
# Question 1 part (b)

# If the equation E = ADB = sum(d[i, i] * (a[i] @ b[i].T)) is true,
# it should be true for any random value in the matrices.
# This is obviously not a proof, we could just get lucky,
# the proof is given after this verification script on random numbers

# Matrix A, a (3, 2) matrix
A = np.random.random((3, 2))
print(f'A =\n{A}', end='\n\n')

# Matrix D, a (2, 2) diagonal matrix
D = np.diag(np.random.random((2, )))
print(f'D =\n{D}', end='\n\n')

# Matrix B, a (2, 4) matrix
B = np.random.random((2, 4))
print(f'B =\n{B}', end='\n\n')

# E is a list of two matrices
# E[0] is the matrix computed using E = A @ D @ B
# E[1] is the matrix computed using E = sum(d[i, i] * (a[i] @ b[i].T))
E = [None] * 2

E[0] = A @ D @ B
print(f'E[0] = \n{E[0]}', end='\n\n')

# To compute E, well add elements according to the formula,
# starting from a Null matrix of dimensions (3, 4)
# A @ D @ B => [(3, 2) @ (2, 2)] @ (2, 4) => (3, 2) @ (2, 4)
# A @ D @ B => (3, 4)
E[1] = np.zeros((3, 4))

# Performing the summation
for i in range(2): # indexes start from 0 instead of 1
    # D[i, i] selects the diagonal elements
    D_i = D[i, i]
    
    # A[:, i] selects the ith columns from A 
    # reshaping to make it compatible with mat_mul
    A_i = (_ := A[:, i]).reshape((_.shape[0], 1))
    
    # B[i] selects the ith row from B
    # reshaping to make it compatible with mat_mul
    B_i = (_ := B[i]).reshape((1, _.shape[0], ))
    
    # Summing after the operations
    E[1] += D_i * (A_i @ B_i)

print(f'E[1] = \n{E[1]}', end='\n\n')

# We can check if the matrices E[0] and E[1] are equal
# To avoid errors arising from floating point numbers,
# we will use the numpy.isclose() method
equal_Es = np.isclose(*E)

print(f'E[0] == E[1] =\n{equal_Es}', end='\n\n')

if equal_Es.all():
    print('Numerically, this is accurate for randomly generated number')
else:
    print(
        'Numerically, this did not work for',
        f'A =\n{A}',
        f'D =\n{D}',
        f'B =\n{B}',
        sep='\n'
    )

A =
[[0.98311357 0.83044497]
 [0.21083687 0.00732811]
 [0.31765662 0.43264151]]

D =
[[0.66850242 0.        ]
 [0.         0.45843598]]

B =
[[0.34333794 0.45176132 0.71370772 0.69347931]
 [0.22001882 0.07629704 0.72742175 0.46823446]]

E[0] = 
[[0.30940888 0.3259505  0.74599227 0.63402377]
 [0.0491309  0.0639298  0.10303725 0.09931543]
 [0.11654745 0.11106606 0.29583453 0.24013215]]

E[1] = 
[[0.30940888 0.3259505  0.74599227 0.63402377]
 [0.0491309  0.0639298  0.10303725 0.09931543]
 [0.11654745 0.11106606 0.29583453 0.24013215]]

E[0] == E[1] =
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

Numerically, this is accurate for randomly generated number


### Question 1 part (b) Mathematical solution

<div style="font-size:15px;">
Let
$A_{3 \times 2} = \begin{bmatrix}a_{11} & a_{12} \\ a_{21} & a_{22} \\ a_{31} & a_{32} \end{bmatrix}$, 
$D_{2 \times 2} = \begin{bmatrix}d_{11} & 0 \\ 0 & d_{22} \end{bmatrix}$ and 
$B_{2 \times 4} = \begin{bmatrix}b_{11} & b_{12} & b_{13} & b_{14} \\ b_{21} & b_{22} & b_{23} & b_{24} \end{bmatrix}$<br>
<br>
To show, $E = ADB = \displaystyle \sum_{i=1}^{2}d_{ii}a_{i}b_{i}^{T}$<br><br>
So, first let's compute $AD$,<br>
$AD = \begin{bmatrix}a_{11} & a_{12} \\ a_{21} & a_{22} \\ a_{31} & a_{32} \end{bmatrix}
\times
\begin{bmatrix}d_{11} & 0 \\ 0 & d_{22} \end{bmatrix}
$<br>
$AD = \begin{bmatrix} 
a_{11} \cdot d_{11} & a_{12} \cdot d_{12} \\
a_{21} \cdot d_{11} & a_{22} \cdot d_{12} \\
a_{31} \cdot d_{11} & a_{32} \cdot d_{12} 
\end{bmatrix}$<br><br>
Now that we know AD, let's compute $ABD$<br>
$ABD = AD \cdot B = \begin{bmatrix} 
a_{11} \cdot d_{11} & a_{12} \cdot d_{12} \\
a_{21} \cdot d_{11} & a_{22} \cdot d_{12} \\
a_{31} \cdot d_{11} & a_{32} \cdot d_{12} 
\end{bmatrix} \times 
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14} \\
b_{21} & b_{22} & b_{23} & b_{24}
\end{bmatrix}$<br>
$ABD = \begin{bmatrix} 
a_{11}  d_{11}  b_{11} + a_{12}  d_{22}  b_{21} &
a_{11}  d_{11}  b_{12} + a_{12}  d_{22}  b_{22} &
a_{11}  d_{11}  b_{13} + a_{12}  d_{22}  b_{23} &
a_{11}  d_{11}  b_{14} + a_{12}  d_{22}  b_{24} \\
a_{21}  d_{11}  b_{11} + a_{22}  d_{22}  b_{21} &
a_{21}  d_{11}  b_{12} + a_{22}  d_{22}  b_{22} &
a_{21}  d_{11}  b_{13} + a_{22}  d_{22}  b_{23} &
a_{21}  d_{11}  b_{14} + a_{22}  d_{22}  b_{24} \\
a_{31}  d_{11}  b_{11} + a_{32}  d_{22}  b_{21} &
a_{31}  d_{11}  b_{12} + a_{32}  d_{22}  b_{22} &
a_{31}  d_{11}  b_{13} + a_{32}  d_{22}  b_{23} &
a_{31}  d_{11}  b_{14} + a_{32}  d_{22}  b_{24} \\
\end{bmatrix}
$&emsp;&emsp;...1<br><br>
Now, let's compute $E$ using $E = \displaystyle \sum_{i=1}^{2}d_{ii}a_{i}b_{i}^{T}$<br>
$E = d_{11}a_{1}b_{1}^{T} + d_{22}a_{2}b_{2}^{T}$<br>
<br>
Computing individual components of $E$,<br>
$d_{11}a_{1}b_{1}^{T} = d_{11} \cdot 
\begin{bmatrix} a_{11} \\ a_{21} \\ a_{31} \end{bmatrix} \times
\begin{bmatrix} b_{11} & b_{12} & b_{13} & b_{14} \end{bmatrix}
$<br>
$d_{11}a_{1}b_{1}^{T} = d_{11} \cdot
\begin{bmatrix}
a_{11}b_{11} & a_{11}b_{12} & a_{11}b_{13} & a_{11}b_{14} \\
a_{21}b_{11} & a_{21}b_{12} & a_{21}b_{13} & a_{21}b_{14} \\
a_{31}b_{11} & a_{31}b_{12} & a_{31}b_{13} & a_{31}b_{14} \\
\end{bmatrix}
$<br>
$d_{11}a_{1}b_{1}^{T} =
\begin{bmatrix}
d_{11}a_{11}b_{11} & d_{11}a_{11}b_{12} & d_{11}a_{11}b_{13} & d_{11}a_{11}b_{14} \\
d_{11}a_{21}b_{11} & d_{11}a_{21}b_{12} & d_{11}a_{21}b_{13} & d_{11}a_{21}b_{14} \\
d_{11}a_{31}b_{11} & d_{11}a_{31}b_{12} & d_{11}a_{31}b_{13} & d_{11}a_{31}b_{14} \\
\end{bmatrix}
$&emsp;&emsp;&emsp;...2<br>
<br>
$d_{22}a_{2}b_{2}^{T} = d_{22} \cdot 
\begin{bmatrix} a_{12} \\ a_{22} \\ a_{32} \end{bmatrix} \times
\begin{bmatrix} b_{21} & b_{22} & b_{23} & b_{24} \end{bmatrix}
$<br>
$d_{22}a_{2}b_{2}^{T} = d_{22} \cdot
\begin{bmatrix}
a_{12}b_{21} & a_{12}b_{22} & a_{12}b_{23} & a_{12}b_{24} \\
a_{22}b_{21} & a_{22}b_{22} & a_{22}b_{23} & a_{22}b_{24} \\
a_{32}b_{21} & a_{32}b_{22} & a_{32}b_{23} & a_{32}b_{24} \\
\end{bmatrix}
$<br>
$d_{22}a_{2}b_{2}^{T} =
\begin{bmatrix}
d_{22}a_{12}b_{21} & d_{22}a_{12}b_{22} & d_{22}a_{12}b_{23} & d_{22}a_{12}b_{24} \\
d_{22}a_{22}b_{21} & d_{22}a_{22}b_{22} & d_{22}a_{22}b_{23} & d_{22}a_{22}b_{24} \\
d_{22}a_{32}b_{21} & d_{22}a_{32}b_{22} & d_{22}a_{32}b_{23} & d_{22}a_{32}b_{24} \\
\end{bmatrix}$&emsp;&emsp;&emsp;...3<br>
<br>
Using Equation 2 and 3,<br>
$E = d_{11}a_{1}b_{1}^{T} + d_{22}a_{2}b_{2}^{T}$<br><br>
$E = 
\begin{bmatrix}
d_{11}a_{11}b_{11} & d_{11}a_{11}b_{12} & d_{11}a_{11}b_{13} & d_{11}a_{11}b_{14} \\
d_{11}a_{21}b_{11} & d_{11}a_{21}b_{12} & d_{11}a_{21}b_{13} & d_{11}a_{21}b_{14} \\
d_{11}a_{31}b_{11} & d_{11}a_{31}b_{12} & d_{11}a_{31}b_{13} & d_{11}a_{31}b_{14} \\
\end{bmatrix}
+ 
\begin{bmatrix}
d_{22}a_{12}b_{21} & d_{22}a_{12}b_{22} & d_{22}a_{12}b_{23} & d_{22}a_{12}b_{24} \\
d_{22}a_{22}b_{21} & d_{22}a_{22}b_{22} & d_{22}a_{22}b_{23} & d_{22}a_{22}b_{24} \\
d_{22}a_{32}b_{21} & d_{22}a_{32}b_{22} & d_{22}a_{32}b_{23} & d_{22}a_{32}b_{24} \\
\end{bmatrix}
$<br><br>
$
E = \begin{bmatrix} 
d_{11}  a_{11}  b_{11} + d_{22}  a_{12}  b_{21} &
d_{11}  a_{11}  b_{12} + d_{22}  a_{12}  b_{22} &
d_{11}  a_{11}  b_{13} + d_{22}  a_{12}  b_{23} &
d_{11}  a_{11}  b_{14} + d_{22}  a_{12}  b_{24} \\
d_{11}  a_{21}  b_{11} + d_{22}  a_{22}  b_{21} &
d_{11}  a_{21}  b_{12} + d_{22}  a_{22}  b_{22} &
d_{11}  a_{21}  b_{13} + d_{22}  a_{22}  b_{23} &
d_{11}  a_{21}  b_{14} + d_{22}  a_{22}  b_{24} \\
d_{11}  a_{31}  b_{11} + d_{22}  a_{32}  b_{21} &
d_{11}  a_{31}  b_{12} + d_{22}  a_{32}  b_{22} &
d_{11}  a_{31}  b_{13} + d_{22}  a_{32}  b_{23} &
d_{11}  a_{31}  b_{14} + d_{22}  a_{32}  b_{24} \\
\end{bmatrix}
$&emsp;&emsp;...4<br>
<br>
Comparing elementwise, we can easily verify that $E$ obtained in <em>Equation $4$</em> is equivalent to the $E$ obtained in <em>Equation $1$</em><br>
Therefore, $E = ADB = \displaystyle \sum_{i=1}^{2}d_{ii}a_{i}b_{i}^{T}$ is $\text{True}$
</div>

In [4]:
# Question 1 part (c)

a = np.arange(20)
A = a.reshape((5, 4))
print(f'A =\n{A}')

A =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [5]:
# Question 1 part (d)

hadamard_product = A * A
print(f'Hadamard Product =\n{hadamard_product}')

Hadamard Product =
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


In [7]:
# Question 2 part (a)

b = np.arange(24)
B = b.reshape((2, 3, 4))

print(f'B = \n{B}')

B = 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
# Question 2 part (b)

B_sum = np.sum(B)

print(f'Sum of elements in B = {B_sum}')

Sum of elements in B = 276


In [12]:
# Question 2 part (c)

C, D = B # obtaining C and D via tuple unpacking

print(f'C =\n{C}')
print(f'D =\n{D}')

C =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
D =
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Question 3

<table style="text-align:center;font-size:16px;">
  <tr>
    <th>Outlook</th>
    <th>Temperature</th>
    <th>Humidity</th>
    <th>Wind</th>
    <th>Played Football (yes/no)</th>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Hot</td>
    <td>High</td>
    <td>Weak</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Hot</td>
    <td>High</td>
    <td>Strong</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Hot</td>
    <td>High</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Mild</td>
    <td>High</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Strong</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Strong</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Mild</td>
    <td>High</td>
    <td>Weak</td>
    <td>No</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Cool</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Mild</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Sunny</td>
    <td>Mild</td>
    <td>Normal</td>
    <td>Strong</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Mild</td>
    <td>High</td>
    <td>Strong</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Overcast</td>
    <td>Hot</td>
    <td>Normal</td>
    <td>Weak</td>
    <td>Yes</td>
  </tr>

  <tr>
    <td>Rain</td>
    <td>Mild</td>
    <td>High</td>
    <td>Strong</td>
    <td>No</td>
  </tr>
</table>