In [1]:
# Setup

import numpy as np

A = np.array([1, -2, 3, 2, 1, -1,]).reshape((2,3)).T
A

array([[ 1,  2],
       [-2,  1],
       [ 3, -1]])

In [2]:
# Question 1 part (a)
# Expected answer is 2, since matrix A has 2 linearly independent column vectors

rank = np.linalg.matrix_rank(A)
print(f'{rank = }') 

rank = 2


In [3]:
# Question 1 part (b)
# The dimensions of U (left singular vectors) are (3 x 2)
# The dimensions of S (singular value matrix) are (2 x 2)
# The dimensions of V (right singular vectors) are (2 x 2)
# K = min(A.shape) => K = min(3, 2) = 2

# Computing the SVD
# The full_matrices parameter has been set to False to only compute
# the relevant/important vectors in the U,S and V matrices
# (not the vectors that will result to 0 after computation)
U, S, V = np.linalg.svd(A, full_matrices=False)

# Make S a diagonal matrix
S = np.diag(S)

# Verification of the dimensions of U (left singular vectors)
print(f'Dimensions of U = {U.shape}')

# Verification of the dimensions of S (singular value matrix)
print(f'Dimensions of S = {S.shape}')

# Verification of the dimensions of V (right singular vectors)
print(f'Dimensions of V = {V.shape}')

Dimensions of U = (3, 2)
Dimensions of S = (2, 2)
Dimensions of V = (2, 2)


In [4]:
# Question 1 part (b) continued
u1 = U[:,0].reshape((U.shape[0], 1))
u2 = U[:, 1].reshape((U.shape[0], 1))

print(f'U =\n{U}', end='\n\n')
print(f'{u1 = }', end='\n\n')
print(f'{u2 = }')

U =
[[-8.16496581e-02 -9.89949494e-01]
 [ 5.71547607e-01 -1.41421356e-01]
 [-8.16496581e-01 -1.86454855e-16]]

u1 = array([[-0.08164966],
       [ 0.57154761],
       [-0.81649658]])

u2 = array([[-9.89949494e-01],
       [-1.41421356e-01],
       [-1.86454855e-16]])


In [5]:
# Question 1 part (b) continued
s1, s2 = S[S != 0]

print(f'S =\n{S}', end='\n\n')
print(f'{s1 = }', end='\n\n')
print(f'{s2 = }')

S =
[[3.87298335 0.        ]
 [0.         2.23606798]]

s1 = 3.872983346207417

s2 = 2.23606797749979


In [6]:
# Question 1 part (b) continued
v1 = V[0, :].reshape((1, V.shape[1]))
v2 = V[1, :].reshape((1, V.shape[1]))

print(f'V =\n{V}', end='\n\n')
print(f'{v1 = }', end='\n\n')
print(f'{v2 = }')

V =
[[-0.9486833   0.31622777]
 [-0.31622777 -0.9486833 ]]

v1 = array([[-0.9486833 ,  0.31622777]])

v2 = array([[-0.31622777, -0.9486833 ]])


In [7]:
# Question 1 part (b) continued
# Verification that u1, u2, s1, s2, v1 and v2 are correct

# Summation to compute A from the SVD [@ is equivalent to np.dot()]
A_from_svd = (s1 * (u1 @ v1)) + (s2 * (u2 @ v2))

print(f'A from SVD =\n{A_from_svd}', end='\n\n')

# Some values here are false due to inexact floating point number comparison
# However, the array printed above should be representative of the correctness
# of the computation.
A_from_svd_compared = A_from_svd == A
print(f'A from SVD compared to original A =\n{A_from_svd_compared}', end='\n\n')

# We can use the numpy.isclose() method to verify that the values are indeed almost equal
are_they_close = np.isclose(A, A_from_svd)
print(f'A from SVD compared to original A using numpy.isclose() =\n{are_they_close}')

A from SVD =
[[ 1.  2.]
 [-2.  1.]
 [ 3. -1.]]

A from SVD compared to original A =
[[False False]
 [False  True]
 [ True  True]]

A from SVD compared to original A using numpy.isclose() =
[[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
# Question 1 part (c)

# Computing B
B = A @ A.T
print(f'B =\n{B}')

B =
[[ 5  0  1]
 [ 0  5 -7]
 [ 1 -7 10]]


In [9]:
# Question 1 part (c) continued
eigen_values, eigen_vectors = np.linalg.eig(B)
eigen_vectors_T = eigen_vectors.T
print(f'Eigen Values =\n{eigen_values}')
print(f'Eigen Vectors =\n{eigen_vectors}')
print(f'Eigen Vectors Transpose =\n{eigen_vectors_T}')

Eigen Values =
[ 1.50000000e+01  5.00000000e+00 -3.96556534e-16]
Eigen Vectors =
[[ 8.16496581e-02  9.89949494e-01  1.15470054e-01]
 [-5.71547607e-01  1.41421356e-01 -8.08290377e-01]
 [ 8.16496581e-01  2.44751686e-16 -5.77350269e-01]]
Eigen Vectors Transpose =
[[ 8.16496581e-02 -5.71547607e-01  8.16496581e-01]
 [ 9.89949494e-01  1.41421356e-01  2.44751686e-16]
 [ 1.15470054e-01 -8.08290377e-01 -5.77350269e-01]]


In [10]:
# Question 1 part (c) continued

# W, W_T, L correspond to W, W.T and Lambda in the question
# M = 3, corresponding to the number of rows or columns in the square matrix B

W = eigen_vectors
W_T = eigen_vectors_T
L = np.diag(eigen_values)

M = B.shape[0] # number of rows
print(f'{M = }')

M = 3


In [11]:
# Question 1 part (c) continued
w1 = W[:, 0].reshape((W.shape[0], 1))
w2 = W[:, 1].reshape((W.shape[0], 1))
w3 = W[:, 2].reshape((W.shape[0], 1))

print(f'w1 =\n{w1}', end='\n\n')
print(f'w2 =\n{w2}', end='\n\n')
print(f'w3 =\n{w3}')

w1 =
[[ 0.08164966]
 [-0.57154761]
 [ 0.81649658]]

w2 =
[[9.89949494e-01]
 [1.41421356e-01]
 [2.44751686e-16]]

w3 =
[[ 0.11547005]
 [-0.80829038]
 [-0.57735027]]


In [12]:
# Question 1 part (c) continued
l1, l2, l3 = L[L != 0]

print(f'{l1 = }')
print(f'{l2 = }')
print(f'{l3 = }')

l1 = 15.000000000000004
l2 = 4.999999999999998
l3 = -3.9655653361030586e-16


In [13]:
# Question 1 part (c) continued
wt1 = W_T[0, :].reshape((1, W_T.shape[0]))
wt2 = W_T[1, :].reshape((1, W_T.shape[0]))
wt3 = W_T[2, :].reshape((1, W_T.shape[0]))

print(f'w.T1 =\n{wt1}', end='\n\n')
print(f'w.T2 =\n{wt2}', end='\n\n')
print(f'w.T3 =\n{wt3}')

w.T1 =
[[ 0.08164966 -0.57154761  0.81649658]]

w.T2 =
[[9.89949494e-01 1.41421356e-01 2.44751686e-16]]

w.T3 =
[[ 0.11547005 -0.80829038 -0.57735027]]


In [14]:
# Question 1 part (c) continued
# Verification that w1, w2, w3, l1, l2, l3, wt1, wt2 and wt3 are correct

# Summation to computer from B the Eigen Decomposition
B_from_eigen_decompostion = (l1 * (w1 @ wt1)) + (l2 * (w2 @ wt2)) + (l3 * (w3 @ wt3))
print(f'B from Eigen Decompostion =\n{B_from_eigen_decompostion}', end='\n\n')

# Similar to the SVD, values here are false due to precision errors of floating point numbers
B_from_eigen_decompostion_compared = B_from_eigen_decompostion == B
print(f'B from Eigen Decomposition compared to original B =',
      f'{B_from_eigen_decompostion_compared}', sep='\n', end='\n\n')

# We can use the numpy.isclose() method to verify that the values are indeed almost equal
are_they_close2 = np.isclose(B, B_from_eigen_decompostion)
print(f'B from Eigen Decomposition compared to original B using numpy.isclose() =',
      f'{are_they_close2}', sep='\n')

B from Eigen Decompostion =
[[ 5.00000000e+00  5.03301555e-15  1.00000000e+00]
 [ 5.03301555e-15  5.00000000e+00 -7.00000000e+00]
 [ 1.00000000e+00 -7.00000000e+00  1.00000000e+01]]

B from Eigen Decomposition compared to original B =
[[False False False]
 [False False False]
 [False False False]]

B from Eigen Decomposition compared to original B using numpy.isclose() =
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Question 2 part (a)

<div data-role="answer" style="font-size: 16px;">
Given,<br>
$H: \{x| g(x) = w^{T}x + b = 0\}$ and $H$ intersects the axes $x_{1}$ and $x_{2}$ at $(5, 0)$ and $(0, 4)$<br>
Where the Hyperplane $H$ is a line, so it has the form<br>
$w_{1}x_{1} + w_{2}x_{2} + b = 0$<br>
<br>
Using the fact that the Hyperplane $H$ intersects the two axes at $(5,0)$ and $(0, 4)$<br>
We can construct two equations<br>
$(w_{1} \times 5) + (w_{2} \times 0) = -b$&emsp;&emsp;$\text{...} 1$<br>
$(w_{1} \times 0) + (w_{2} \times 4) = -b$&emsp;&emsp;$\text{...} 2$<br>
<br>
Since $-b$ is a constant, <em>Equation 1</em> is equal to <em>Equation 2</em><br>
$5w_{1} + 0 \times w_{2} = 0 \times w_{1} + 4w_{2}$&emsp;&emsp;$\text{...} 3$<br>
Simplifiying <em>Equation 3</em>, we get,<br>
$5w_{1} = 4w_{2}$<br>
$w_{1} = \frac{4}{5}w_{2}$&emsp;&emsp;$\text{...} 4$<br>
<br>
This however is an equation in $2$ variables, and therefore has no unique solution<br>
<br>
The required unique solution comes from the given condition $|w^{T}| = 1$<br>
So, $\sqrt{w_{1}^{2} + w_{2}^{2}} = 1$&emsp;&emsp;$\text{...} 5$<br>
Which is derived from the formula for distance/length in the Eucleadean space or the $L_{2}$ norm<br>
<br>
Substituting the value of $w_{1}$ from <em>Equation 4</em> in <em>Equation 6</em> and simplifiying, we get,<br>
$\sqrt{w_{1}^{2} + w_{2}^{2}} = 1$<br>
$\sqrt{(\frac{4}{5}w_{2})^{2} + w_{2}^{2} } = 1$<br>
$\sqrt{\frac{16}{25}w_{2}^{2} + w_{2}^{2}} = 1$<br>
$\sqrt{\frac{41}{25}w_{2}^{2}} = 1$<br>
$\sqrt{\frac{41}{25}}w_{2} = 1$<br>
$w_{2} = \frac{5}{\sqrt{41}}$&emsp;&emsp;$\text{...} 6$<br>
<br>
Using <em>Equation 6</em> in <em>Equation 4</em>, we get<br>
$w_{1} = \frac{4}{5}(\frac{5}{\sqrt{41}})$<br>
$w_{1} = \frac{4}{\sqrt{41}}$&emsp;&emsp;$\text{...} 7$<br>
<br>
Using <em>Equation 7</em> in <em>Equation 1</em> and simplifiying, we can obtain $\text{b}$<br>
$(w_{1} \times 5) + (w_{2} \times 0) = -b$<br>
$b = -5w_{1}$<br>
$b = -5(\frac{4}{\sqrt{41}})$<br>
$b = \frac{-20}{\sqrt{41}}$<br>
<br>
So,<br>
$w = \begin{bmatrix}w_{1}\\ w_{2}\end{bmatrix}=\begin{bmatrix}\frac{4}{\sqrt{41}}\\ \frac{5}{\sqrt{41}} \end{bmatrix}$<br>
$b = \frac{-20}{\sqrt{41}}$<br>
</div>

In [15]:
# Question 2 part (b)
# r's sign represents if it's on the same or opposite side of the origin
w = np.array([4, 5]) / (41**0.5)
b = -20 / (41 ** 0.5)

def g(x: np.ndarray) -> float:
    return w[0]*x[0] + w[1]*x[1] + b

def r(x: np.ndarray) -> float:
    # np.hypot computes the hypotenuse of a right triangle, equivalent to Eucleadean distance
    return g(x) / np.hypot(*w) 
print(r(np.array([4.5, 3])))

2.030258904551879
