In [1]:
# Question 1

# Setup
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

filename = 'winequality-red.csv'

data = np.genfromtxt(filename, delimiter=',')
X = data[1:, :-1]
y = data[1:, -1]

print(f'{X.shape = }')
print(f'{y.shape = }')

X.shape = (1599, 11)
y.shape = (1599,)


In [2]:
# Question 1 continued
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(f'{X_train.shape = }')
print(f'{y_train.shape = }')
print(f'{X_test.shape = }')
print(f'{y_test.shape = }')

X_train.shape = (1279, 11)
y_train.shape = (1279,)
X_test.shape = (320, 11)
y_test.shape = (320,)


In [3]:
# Question 1 continued
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(f'{y_pred.shape = }')

y_pred.shape = (320,)


In [5]:
# Question 1 continued
acc = accuracy_score(y_test, y_pred) * 100
cm = confusion_matrix(y_test, y_pred)

print(f'Accuracy Score=\n{acc:.5}%')
print(f'Confusion Matrix =\n{cm}')

Accuracy Score=
49.688%
Confusion Matrix =
[[ 0  2  0  0  0  0]
 [ 0  1  6  2  0  0]
 [ 0  7 86 29  3  0]
 [ 0  3 59 47 22  0]
 [ 0  1  5 15 25  1]
 [ 0  0  0  1  5  0]]
