In [1]:
# Setup

%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np

plt.style.use('dark_background')

In [2]:
# Question 1 part (a)

# Setup
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

classification_rate = lambda x: np.trace(x) / np.sum(x)

filename = 'wine.csv'

data = np.genfromtxt(filename, delimiter=',')
# The first element is nan for an unknown reason
data[0, 0] = 14.23

X = data[:, :-1]
y = data[:, -1]

print(f'{X.shape = }')
print(f'{y.shape = }')

X.shape = (178, 13)
y.shape = (178,)


In [3]:
# Question 1 part (a) continued

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(f'{X_train.shape = }')
print(f'{y_train.shape = }')
print(f'{X_test.shape = }')
print(f'{y_test.shape = }')

X_train.shape = (142, 13)
y_train.shape = (142,)
X_test.shape = (36, 13)
y_test.shape = (36,)


In [6]:
# Question 1 part (a) continued
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
correct = classification_rate(cm)
print(f'Confusion Matrix =\n{cm}')
print(f'Classification Rate = {correct:.3f}')

Confusion Matrix =
[[13  0  0]
 [ 0  9  0]
 [ 0  0 14]]
Classification Rate = 1.000


In [ ]:
# Question 1 part (b)

# Setup
from sklearn.tree import DecisionTreeClassifier


model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
correct = classification_rate(cm)
print(f'Confusion Matrix =\n{cm}')
print(f'Classification Rate = {correct:.3f}')