In [1]:
# Question 1

# Setup
import numpy as np

X = np.array([[1, 2, 3,], [2, -1, 0,],]).T
y = np.array([[0, 1, 0,],]).T
w1 = np.array([[1, 2, 0,], [-1, 0, 3,],]) / 10
w2 = np.array([[5e-2, -1e-1, 2e-1,],]).T

print(f'{X.shape = }')
print(f'{y.shape = }')
print(f'{w1.shape = }')
print(f'{w2.shape = }')

X.shape = (3, 2)
y.shape = (3, 1)
w1.shape = (2, 3)
w2.shape = (3, 1)


In [2]:
def square_loss(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return np.mean((y_true - y_pred) ** 2)

def sigmoid(X: np.ndarray) -> np.ndarray:
    return (np.exp(-X) + 1) ** -1

In [3]:
U1 = np.around(X @ w1, 3)
print(f'U1\n{U1}')

U1
[[-0.1  0.2  0.6]
 [ 0.3  0.4 -0.3]
 [ 0.3  0.6  0. ]]


In [4]:
Z1 = np.around(sigmoid(U1), 3)
print(f'Z1\n{Z1}')

Z1
[[0.475 0.55  0.646]
 [0.574 0.599 0.426]
 [0.574 0.646 0.5  ]]


In [5]:
U2 = np.around(Z1 @ w2, 3)
print(f'U2:\n{U2}')

U2:
[[0.098]
 [0.054]
 [0.064]]


In [6]:
Z2 = np.around(sigmoid(U2), 3)
print(f'Z2:\n{Z2}')

Z2:
[[0.524]
 [0.513]
 [0.516]]


In [7]:
delta_l2 = np.around(Z2 * (1-Z2) * (Z2 - y), 3)
print(f'Delta layer 2\n{delta_l2}')

Delta layer 2
[[ 0.131]
 [-0.122]
 [ 0.129]]


In [8]:
delta_l1 = np.around(delta_l2 @ w2.T, 3)
print(f'Delta layer 1\n{delta_l1}')

Delta layer 1
[[ 0.007 -0.013  0.026]
 [-0.006  0.012 -0.024]
 [ 0.006 -0.013  0.026]]


In [9]:
dw2 = np.around(Z1.T @ delta_l2, 3)
print(f'Layer 2 weight gradient\n{dw2}')

Layer 2 weight gradient
[[0.066]
 [0.082]
 [0.097]]


In [10]:
dw1 = np.around(X.T @ delta_l1, 3)
print(f'Layer 1 weight gradient\n{dw1}')

Layer 1 weight gradient
[[ 0.013 -0.028  0.056]
 [ 0.02  -0.038  0.076]]
